### ISSUE TITLE
install.sh 内含 linux 命令，在 windows 下无效

### ISSUE THREAD

**Issue by Dreamer-Somebody** [AIFSH/MyHeyGen#12]
![image](https://github.com/AIFSH/MyHeyGen/assets/8341974/2e015624-f108-4487-a44a-6579a86cff4c)

apt 命令是 linux 下的命令，在 windows 下执行会失败，这个工具支持 windows 吗？

**Comment by Dreamer-Somebody** [comment]
还有一个问题是，google drives 上的  weights 和 checkpoints 下不下来，开了翻墙也下不下来，有没有便捷的网盘链接呢？

**Comment by AIFSH** [comment]
apt used to install ffmpeg on Linux

**Comment by LeXwDeX** [comment]
你需要手工安装ffmpeg，并配置系统环境变量。
