### ISSUE TITLE
Development proposal

### ISSUE THREAD

**Issue by BrasD99** [AIFSH/MyHeyGen#21]
Hi. I am a contributor to HeyGenClone. I see that most of the people came to me, thanks to you and your project. Maybe we should combine our efforts with you, because we are working on the same task?

**Comment by AIFSH** [comment]
yes，thanks  for your great work，i debug some code based on your heygenclone project and make it more available for Chinese.

**Comment by BrasD99** [comment]
I see that you have switched to XTTS. Does it really clone Chinese voice better?

**Comment by AIFSH** [comment]
but i don't think that combination is necessary for some reason like the network can't connect  for most Chinese in translator.py and so on.

**Comment by AIFSH** [comment]
> I see that you have switched to XTTS. Does it really clone Chinese voice better?

yes，it support 16 languages now! And video-retalking have  a good support for Chinese voice

**Comment by BrasD99** [comment]
> > I see that you have switched to XTTS. Does it really clone Chinese voice better?
> 
> yes，it support 16 languages now! And video-retalking have a good support for Chinese voice

Thanks! I'll check this out and implement in HeyGenClone. By the way, yesterday I rolled out an update from the mapping codes (tts and googletrans have different ones), and soon I will start making UI, I hope you will be interested!

**Comment by AIFSH** [comment]
> > > I see that you have switched to XTTS. Does it really clone Chinese voice better?
> > 
> > yes，it support 16 languages now! And video-retalking have a good support for Chinese voice
> 
> Thanks! I'll check this out and implement in HeyGenClone. By the way, yesterday I rolled out an update from the mapping codes (tts and googletrans have different ones), and soon I will start making UI, I hope you will be interested!

looking for your huge great work！

**Comment by BrasD99** [comment]
Btw, how i can contact you? Maybe you have Telegram?

**Comment by AIFSH** [comment]
> Btw, how i can contact you? Maybe you have Telegram?

![mmexport1699698402069.jpg](https://github.com/AIFSH/MyHeyGen/assets/149982694/31207c08-7d01-4bc3-9cd0-78238ebd8535)
