### ISSUE TITLE
macos arm架构可以运行吗

### ISSUE THREAD

**Issue by weiraneve** [AIFSH/MyHeyGen#27]
尝试了多次，最终因为numpy的版本在macos的其他python库依赖冲突下，失败了。

**Comment by AIFSH** [comment]
numpy=1.22.2，no matter other error，just run

**Comment by weiraneve** [comment]
```
Macos M1pro

python 3.10.1

numpy==1.22.2
TTS==0.20.2
tensorflow==2.13.0
```

以上是macos m系列芯片环境上关键依赖的版本，以及代码改动

`MyHeyGen/core/voice_cloner.py", line 7`的代码改动，将`gpu=True`改为`gpu=False`
```python
self.api = TTS(config["TTS_MODEL"],gpu=False)
```
