### ISSUE TITLE
推理一直卡在这个地方

### ISSUE THREAD

**Issue by gaoxiaowei** [AIFSH/MyHeyGen#28]
You can edit it in config.json HUMAN_TRANS as 1 to enable human trans mode
final translate result:Strive to become one of the world's leading internet security companies with their own innovation ability and teamwork spirit
 > Text splitted to sentences.
["Strive to become one of the world's leading internet security companies with their own innovation ability and teamwork spirit"]
 > Processing time: 10.073597431182861
 > Real-time factor: 1.3948233155680578
[Step 5] Creating final speech audio
Video-retalking merge speech voice and video, creating output!!!
/usr/local/lib/python3.10/dist-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[Info] Using cuda for inference.
[Step 0] Number of frames available for inference: 780
[Step 1] Landmarks Extraction in Video.
landmark Det:: 100% 780/780 [00:46<00:00, 16.74it/s]
[Step 2] 3DMM Extraction In Video:: 100% 780/780 [00:13<00:00, 56.73it/s]
using expression center
Load checkpoint from: checkpoints/DNet.pt
Load checkpoint from: checkpoints/LNet.pth
Killed
^C

**Comment by lmpeng12** [comment]
建议先去调通video-retalking的推理代码再运行好点

**Comment by AIFSH** [comment]
cache small or video too long
