### ISSUE TITLE
some issue when i meet

### ISSUE THREAD

**Issue by lmpeng12** [AIFSH/MyHeyGen#29]
Front part
After applying for a token, the TTS module needs to click in and fill in the information before it can be used.
2. It is recommended to obtain the local path during runtime and then run the video_ Retailing # [Step 6] Using video retailing merge speech voice and video, creating output------------------------------------------
#Get the current working directory
Current_ Dir=os. getcwd()
#Splicing Path
#Video_ File_ Path=os. path. coin (current_dir, video_file_path. replace ('./', '/'))
Video_ File_ Path=current_ Dir+video_ File_ Path. replace ('./', '/')
Video_ Retalking section
If using an advanced version of face alignment, remember to change 2d to TWO_ D
2. MyHeyGen main/video retail/third_ Change line 196 of part/face3d/util/preprocess.py to trans_ Params=np. array ([w0, h0, s, t [0,0], t [1,0]])
3. The effect depends on the individual's choice of model adjustment
--------------------------------Chinese------------------------------
前边部分
1.申请token之后，TTS模块还需要点进去填写信息，才能使用。
2.建议在运行的时候获取本地路径，再运行video_retalking # [Step 6] Using video-retalking merge speech voice and video, creating output ------------------------------------------
            # 获取当前工作目录
            current_dir = os.getcwd()
            # 拼接路径
            # video_file_path = os.path.join(current_dir, video_file_path.replace('./','/'))
            video_file_path = current_dir + video_file_path.replace('./','/')
3.建议申请完百度api之后测下能够正常翻译再进行后续操作
video_retalking部分
1.如果使用高级版本的face-alignment，记得将2d,改为TWO_D
2.MyHeyGen-main/video-retalking/third_part/face3d/util/preprocess.py 的196 行改为trans_params = np.array([w0, h0, s, t[0,0], t[1,0]])
3.效果看个人去选择模型调整

**Comment by AIFSH** [comment]
nice (👍ᐛ )

**Comment by lmpeng12** [comment]
语言修改参考作者的方案[https://github.com/AIFSH/MyHeyGen/issues/25](url)
