### ISSUE TITLE
heygen/video-retalking/inference.py", line 40, in main     raise ValueError('--face argument must be a valid path to video/image file') ValueError: --face argument must be a valid path to video/image file

### ISSUE THREAD

**Issue by lucasjinreal** [AIFSH/MyHeyGen#33]
**heygen/video-retalking/inference.py", line 40, in main
    raise ValueError('--face argument must be a valid path to video/image file')
ValueError: --face argument must be a valid path to video/image file**

**Comment by AIFSH** [comment]
Absolute path
