### ISSUE TITLE
翻译后的语音和视频时长对不上怎么办

### ISSUE THREAD

**Issue by geniuslmd** [AIFSH/MyHeyGen#35]
试了两个视频，翻译后语音时长都超过原视频，原视频结束后就是一张图然后嘴巴在讲话

**Comment by geniuslmd** [comment]
https://github.com/AIFSH/MyHeyGen/assets/39125055/09f2928f-4cf2-46d9-8edc-b2d34f7e0507

**Comment by AIFSH** [comment]
fixed,git pull

**Comment by geniuslmd** [comment]
> fixed,git pull

Tq
