### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by terry** [AIFSH/MyHeyGen#6]
The error info as below:

root@autodl-container-aeda11a5fa-e810073a:~/autodl-tmp/MyHeyGen# python translate.py ./test/src.mp4 'zh-cn' -o ./test/out_zh.mp4
output_language:zh-cn
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.1.1. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../.cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.0.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.1.0+cu121. Bad things might happen unless you revert torch to 1.x.

Could not download 'pyannote/speaker-diarization' pipeline.
It might be because the pipeline is private or gated so make
sure to authenticate. Visit https://hf.co/settings/tokens to
create your access token and retry with:

   >>> Pipeline.from_pretrained('pyannote/speaker-diarization',
   ...                          use_auth_token=YOUR_AUTH_TOKEN)

If this still does not work, it might be because the pipeline is gated:
visit https://hf.co/pyannote/speaker-diarization to accept the user conditions.
Traceback (most recent call last):
  File "/root/autodl-tmp/MyHeyGen/translate.py", line 22, in <module>
    translate(
  File "/root/autodl-tmp/MyHeyGen/translate.py", line 11, in translate
    engine = Engine(config, output_language)
  File "/root/autodl-tmp/MyHeyGen/core/engine.py", line 42, in __init__
    self.diarize_model = DiarizationPipeline(use_auth_token=config['HF_TOKEN'])
  File "/root/autodl-tmp/MyHeyGen/core/whisperx/diarize.py", line 18, in __init__
    self.model = Pipeline.from_pretrained(model_name, use_auth_token=use_auth_token,).to(device)
AttributeError: 'NoneType' object has no attribute 'to'

**Comment by AIFSH** [comment]
need huggingface token

**Comment by lmpeng12** [comment]
创建这个token，需要注意什么，我需要怎么命名和放在对应的文件夹中？

**Comment by yiyayamaya** [comment]
# 1. visit hf.co/pyannote/speaker-diarization and accept user conditions
# 2. visit hf.co/pyannote/segmentation and accept user conditions
# 3. visit hf.co/settings/tokens to create an access token
# 4. instantiate pretrained speaker diarization pipeline

https://huggingface.co/pyannote/speaker-diarization
