### ISSUE TITLE
Got killed in step5 without further log

### ISSUE THREAD

**Issue by wttat** [AIFSH/MyHeyGen#7]
The program got killed in last step, could not be sure which part could be the limit? 
I am using 8vcpu/32G MEM/1*A10G(24G) ,the GPU is better than T4, my video is about 4mins.

[Step 5] Creating final speech audio
Video-retalking merge speech voice and video, creating output!!!
/home/ubuntu/.local/lib/python3.10/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[Info] Using cuda for inference.
[Step 0] Number of frames available for inference: 5599
Killed

![image](https://github.com/AIFSH/MyHeyGen/assets/29791466/9fc8bd90-0425-4192-b78f-d78501a8c2a8)

**Comment by AIFSH** [comment]
video too long，split in 2 mins and try again！this error due to cache out of memory
