### ISSUE TITLE
python translate.py 报错

### ISSUE THREAD

**Issue by gaoxiaowei** [AIFSH/MyHeyGen#8]
[Info] Using cuda for inference.
[Step 0] Number of frames available for inference: 57
[Step 1] Landmarks Extraction in Video.
Downloading: "https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth" to /root/.cache/torch/hub/checkpoints/s3fd-619a316812.pth
100% 85.7M/85.7M [01:11<00:00, 1.26MB/s]
Downloading: "https://www.adrianbulat.com/downloads/python-fan/2DFAN4-cd938726ad.zip" to /root/.cache/torch/hub/checkpoints/2DFAN4-cd938726ad.zip
100% 91.9M/91.9M [00:17<00:00, 5.51MB/s]
landmark Det:: 100% 57/57 [00:23<00:00,  2.41it/s]
[Step 2] 3DMM Extraction In Video::   0% 0/57 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/content/MyHeyGen/video-retalking/inference.py", line 367, in <module>
    main()
  File "/content/MyHeyGen/video-retalking/inference.py", line 102, in main
    trans_params, im_idx, lm_idx, _ = align_img(frame, lm_idx, lm3d_std)
  File "/content/MyHeyGen/video-retalking/third_part/face3d/util/preprocess.py", line 196, in align_img
    trans_params = np.array([w0, h0, s, t[0], t[1]])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

**Comment by xufengnian** [comment]
修改numpy版本，可以使用pip install numpy==1.23.1
